TheWidlarzGroup/rn-emoji-keyboard

package.json
Add package description in package.json to fix npm links
=> docs / add package description to fix npm links

src/components/EmojiCategory.tsx, src/store/reducers/RecentEmojiReducer.ts, src/store/reducers/index.ts, src/store/useKeyboardStore.ts
Feature aims to persist keyboard state between components, without using context or external libs.
=> feat: add global recently used store

.github/workflows/lint.yml, .github/workflows/tsc.yml, .github/workflows/typescript.yml
Setup github Actions for:
* install dependencies
* check lint 
* check typescript
Closes #8
=> chore / setup basic pipeline

src/components/EmojiCategory.tsx
=> Fix / prevent pressing blank emoji

README.md, src/components/SearchBar.tsx, src/contexts/KeyboardContext.tsx, src/contexts/KeyboardProvider.tsx
**What changed:**
* Added props:
* `searchBarStyles` ViewStyle
* `searchBarTextStyles` ViewStyle
* `searchBarPlaceholderColor` string
* updated README 
**Preview (ie dark theme):**
=> Feature / search bar customization

src/index.tsx, src/translation/ko.ts
thanks for your project!
i added south korean language
=> add south korea language

src/contexts/KeyboardProvider.tsx
Allows to search emoji by directly typing the emoji 👌
=> Allow search by emoji

src/components/SingleEmoji.tsx
=> Fix: transparent emojis on Android devices

src/components/EmojiCategory.tsx, src/components/EmojiStaticKeyboard.tsx
=> fix: add ability to select emoji while keyboard is open

LICENSE
Update LICENSE copyright notice from "Jakub Grzywacz" to "The Widlarz Group sp. z o.o. https://thewidlarzgroup.com/"
=> Update LICENSE copyright notice

README.md, src/index.tsx, src/translation/pt.ts
This PR merge changes from #65 authored by @urboypx
- add portuguese translation (pt.ts)
- add pt.ts to index.tsx file
- update README
=> feat: added portuguese translation

README.md, src/index.tsx, src/translation/ru.ts, src/translation/ua.ts
Original PR made by @vitaliyirtlach #56
=> Feature / Ukranian and Russiaan translation

docs/docs/documentation/internationalization.md, src/index.tsx, src/translation/cs.ts
=> feat: add cs translation

docs/docs/documentation/internationalization.md, src/index.tsx, src/translation/tr.ts
Turkish translations are added
=> feat: turkish translations

docs/docs/api/modal.md, example/src/App.tsx, example/src/Basic/CategoryChangeGesture.tsx, example/src/Examples/Examples.tsx, src/components/Categories.tsx, src/components/EmojiStaticKeyboard.tsx, src/contexts/KeyboardContext.tsx
This pr adds new props `enableCategoryChangeGesture` which let user to change category with horizontal swipe
Follow provided documentation and check added usage example
=> feature: enable gesture to change emoji category with horizontal swipe gesture

src/components/EmojiCategory.tsx, src/contexts/KeyboardProvider.tsx, src/store/reducers/RecentEmojiReducer.ts, src/utils/skinToneSelectorUtils.ts
closes https://github.com/TheWidlarzGroup/rn-emoji-keyboard/issues/108
=> fix: allow to change emoji tone on re-selection

package.json, yarn.lock
This is the latest recommended version
=> Core: Upgrade react-native-svg

package.json
https://github.com/TheWidlarzGroup/rn-emoji-keyboard/issues/120
=> fix: changed types path in package.json

src/translation/ko.ts
Hi, thanks for your work!
I found improper translation in Korean, so here's the improved change 😄
=> fix: translation in Korean

docs/docs/documentation/internationalization.md, src/index.tsx, src/translation/se.ts
Adds the Swedish translation
Changes:
- Adding new translation, sugested in https://github.com/TheWidlarzGroup/rn-emoji-keyboard/issues/164
=> feat: adding swedish translations

docs/docs/documentation/Examples/selected_emojis.md
=> fix: update selected_emojis.md
